name: pretty_diox_logger
description: Pretty Diox logger is a Diox interceptor that logs network calls in a pretty, easy to read format.
version: 1.3.2
homepage: https://github.com/dmakwt/pretty_diox_logger

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  diox: ^5.0.0
